services:
  docs:
    image: app_cunsole_local_docs
    container_name: app_cunsole_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./app_cunsole:/app/app_cunsole:z
    ports:
      - '9000:9000'
    command: /start-docs
